stages:
  prepare_data:
    cmd: python3 prepare_data.py
    deps:
    - prepare_data.py
    outs:
    - cifar10
  train:
    cmd: python3 main.py
    deps:
    - cifar10
    - main.py
    - modeling
    outs:
    - samples