defaults:
  - base_config
  - _self_
data:
  augmentations: 
    RandomHorizontalFlip:
      _target_: transforms.RandomHorizontalFlip
      p: 0.5
    RandomVerticalFlip:
      _target_: transforms.RandomHorizontalFlip
      p: 0.5
optimizer:

scheduler:
